---
- name: Setup FOOD Application in g1 servers
  hosts: all
  become: yes
  vars:
    port_number: 8080

  tasks:
  - name: Install HTTPD in g1
    package:
      name: httpd
      state: present
    when: ansible_distribution == "CentOS"

  - name: Starting HTTP in g1
    service:
      name: httpd
      state: started
    when: ansible_distribution == "CentOS"

  - name: Enabling HTTP in g1
    service:
      name: httpd
      enabled: true
    when: ansible_distribution == "CentOS"

  - name: Install GIT in g1
    package:
      name: git
      state: present
    when: ansible_distribution == "CentOS"

  - name: Cloning ECOMM code to g1
    git:
      dest: /var/www/html
      repo: https://github.com/ravi2krishna/ecomm.git
    when: ansible_distribution == "CentOS"

  - name: Enable SELINUX in g1
    selinux:
      policy: targeted
      state: permissive
    when: ansible_distribution == "CentOS"

  - name: Updating HTTPD config in g1
    template:
      src: httpd.j2
      dest: /etc/httpd/conf/httpd.conf
    when: ansible_distribution == "CentOS"
    notify:
    - Restart HTTPD

  - name: Upadate APT in ubuntu
    apt:
      update_cache: true
    when: ansible_distribution == "Ubuntu"

  - name: Install APACHE2 in u2
    package:
      name: apache2
      state: present
    when: ansible_distribution == "Ubuntu"

  - name: Starting APACHE2 in u2
    service:
      name: apache2
      state: started
    when: ansible_distribution == "Ubuntu"
          
  - name: Enabling APACHE2 in u2
    service:
      name: apache2
      enabled: true
    when: ansible_distribution == "Ubuntu"
 
  - name: Updating apache2 config in u2
    template:
      src: apache2.j2
      dest: /etc/apache2/ports.conf
    when: ansible_distribution == "Ubuntu"
    notify:
    - Restart APACHE2
  
  handlers:
  - name: Restart HTTPD
    service:
      name: httpd
      state: restarted
    when: ansible_distribution == "CentOS"

  - name: Restart APACHE2
    service:
      name: apache2
      state: restarted
    when: ansible_distribution == "Ubuntu"
          

...
